name: Deploy do Dashboard para o GitHub Pages

on:
  push:
    branches: ["master", "main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Corrigido de 'node-size' para 'node-version'
          cache: 'npm'

      - name: Instalar dependências e buildar
        run: |
          npm install # Mudamos de 'npm ci' para 'npm install' para evitar erros de trava de pacotes
          npm run build

      - name: Configurar Páginas
        uses: actions/configure-pages@v5

      - name: Upload do Artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
